# HTTP-Server-Port
quarkus.http.port=8080

# JWT-Konfiguration
mp.jwt.verify.publickey.location=META-INF/resources/publicKey.pem
smallrye.jwt.sign.key.location=META-INF/resources/privateKey.pem
mp.jwt.verify.issuer=chatbotBackend

# Aktiviere Sicherheitsmechanismen
#quarkus.http.auth.basic=true
quarkus.http.auth.policy.test.paths=/auth/test
quarkus.http.auth.policy.test.policy=permit
quarkus.http.auth.policy.public.paths=/auth/login,/auth/register
quarkus.http.auth.policy.public.policy=permit



# PostgreSQL
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=chatbot_user
quarkus.datasource.password=chatbot_password
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/chatbot_db

#MongoDB-Verbindung
quarkus.mongodb.connection-string=mongodb+srv://chatbotUser:chatbot2025@chatbot.owkrg.mongodb.net/?retryWrites=true&w=majority&appName=Chatbot
quarkus.mongodb.database=chatbotDB
quarkus.mongodb.panache.package=com.example.chatbot.entityMongoDB


#Logs f?r MongoDB anzeigen
quarkus.mongodb.log-commands=true

# Flyway-Konfiguration
quarkus.flyway.migrate-at-start=true
quarkus.flyway.schemas=public
quarkus.flyway.locations=db/migration
quarkus.flyway.baseline-on-migrate=true
quarkus.flyway.baseline-version=3


# Hibernate-Einstellungen (f?r automatische Schemaerstellung) ->aktuell nur Flyway f?r die Datenbank
#quarkus.hibernate-orm.sql-load-script=no-file
quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.validate-schema=true


# CORS (optional)
quarkus.http.cors=true
quarkus.http.cors.origins=*

#LLM-API
llm-api/mp-rest/url=https://api.openai.com
llm-api/mp-rest/connectTimeout=5000
llm-api/mp-rest/readTimeout=5000

# OpenAI API-Schlüssel
llm.api.key=${LLM_API_KEY}