# HTTP-Server-Port
quarkus.http.port=8080

# JWT-Konfiguration
mp.jwt.verify.publickey.location=META-INF/resources/publicKey.pem
smallrye.jwt.sign.key.location=META-INF/resources/privateKey.pem
mp.jwt.verify.issuer=chatbotBackend

# Aktiviere Sicherheitsmechanismen
#quarkus.http.auth.basic=true
quarkus.http.auth.policy.test.paths=/auth/test
quarkus.http.auth.policy.test.policy=permit
quarkus.http.auth.policy.public.paths=/auth/login,/auth/register
quarkus.http.auth.policy.public.policy=permit



# PostgreSQL
quarkus.datasource."app".db-kind=postgresql
quarkus.datasource."app".jdbc.url=jdbc:postgresql://localhost:5432/chatbot_db
quarkus.datasource."app".username=chatbot_user
quarkus.datasource."app".password=chatbot_password
quarkus.hibernate-orm.datasource=app

#PostgreSQL Uni-Testdatenbank
quarkus.datasource."unidb".db-kind=postgresql
quarkus.datasource."unidb".jdbc.url=jdbc:postgresql://localhost:5433/unidb
quarkus.datasource."unidb".username=unia_admin
quarkus.datasource."unidb".password=unidb_password

#MongoDB-Verbindung
quarkus.mongodb.connection-string=mongodb+srv://michaelzitz999:3T7I6ByEDfiogLXm@clusterdb.atxkcie.mongodb.net/?retryWrites=true&w=majority&appName=Clusterdb
quarkus.mongodb.database=chatbotDB
quarkus.mongodb.panache.package=com.example.chatbot.entityMongoDB


#Logs f?r MongoDB anzeigen
quarkus.mongodb.log-commands=true

# Flyway-Konfiguration
quarkus.flyway."app".migrate-at-start=true
quarkus.flyway."app".schemas=public
quarkus.flyway."app".locations=db/migration
quarkus.flyway."app".baseline-on-migrate=true
quarkus.flyway."app".baseline-version=3


# Hibernate-Einstellungen (f?r automatische Schemaerstellung) ->aktuell nur Flyway f?r die Datenbank
#quarkus.hibernate-orm.sql-load-script=no-file
quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.validate-schema=true


# CORS (optional)
quarkus.http.cors=true
quarkus.http.cors.origins=*

#LLM-API
llm-api/mp-rest/url=https://api.openai.com
llm-api/mp-rest/connectTimeout=5000
llm-api/mp-rest/readTimeout=5000

# OpenAI API-Schlüssel
llm.api.key=${LLM_API_KEY}